IN-197-notifications-dropdown-fix
BiteCreators/inct-bc pull request #80
Opened 2024-11-05 18:49 UTC by DePacos

2024-11-06 10:11 UTC, tapuru requested changes
![2024-11-06_15-10](https://github.com/user-attachments/assets/019f7f6b-43cf-4706-a670-4f5f507b2af3)
иконка уехала вниз немного, и при открытии дропдауна перестала перекрашиваться в синий

2024-11-07 06:00 UTC, tapuru requested changes
надо ещё немного подправить условие с иконками, а то если не передать вообще icon open, то когда открываешь иконка пропадает полностью

2024-11-07 06:02 UTC, tapuru commented
const incon = open ? iconButtonOpen || icon || <placeholder>  : icon || <paceholder>

2024-11-07 06:02 UTC, tapuru commented
или как-то так

2024-11-07 17:41 UTC, DePacos commented
Поправил.

2024-11-08 08:53 UTC, tapuru approved these changes

2024-11-08 08:53 UTC, merged